Cascade: Detect specific objects (e.g., faces, cars)

Contour Detection is best when you need to segment and detect the shape of an object in an image.

Cascade Classifiers are more suited for specific object detection tasks like face or pedestrian detection, especially when working with pre-trained models.

Edge Detection is useful when you need to identify outlines but don't necessarily need to detect the full object.

Corner Detection is helpful when you're looking for distinctive points to track or match features between different images.

Best scalar factor for face btw 1.1 and 1.5
for eyes 1.1 (zoom in)

cv2.CascadeClassifier: This function is used to load a pre-trained Haar Cascade classifier, which detects specific objects (in this case, faces and eyes) based on the features it has learned during training.

cv2.data.haarcascades: This is a path to the directory where OpenCV stores pre-trained Haar Cascade XML files. 

In [8]:
import cv2
import numpy as np 
# Load the pre-trained classifiers
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
img=cv2.imread(r"c:\Users\asus\Downloads\TheAIEngineers-Notebooks-master\ComputerVisionNotebooks\DATA\Nadia_Murad.jpg")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces=face_cascade.detectMultiScale(gray,1.3)
#1.5 is the scale factor that determines how much the image is resized during detection.
#5 is the minimum number of neighbors that a detected region must have to be considered a valid face.
#faces is a list of rectangles where each rectangle corresponds to a detected face.
#Each rectangle is described by 4 values: (x, y, w, h) — top-left corner coordinates, width, and height of the face.
print(len(faces))
print(faces[0])
eye=eye_cascade.detectMultiScale(gray,1.2)
print(len(eye))
print(eye)
   
for(x,y,w,h) in faces:
    cv2.rectangle(img,[x,y],[w+x,h+y],[255,0,0],2)
    
for(i,j,z,l) in eye:
     cv2.rectangle(img,(i,j),(i+z,l+j),[0,255,0],2)
cv2.imshow('faces',img)
cv2.waitKey(0)



1
[ 56 143 272 272]
2
[[203 212  63  63]
 [108 222  58  58]]


-1

In [9]:
import cv2
import numpy as np 
# Load the pre-trained classifiers
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
img=cv2.imread(r"C:\Users\asus\Desktop\Computer Vision\lab3\face.PNG")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
eyes=eye_cascade.detectMultiScale(gray,1.1,5)
#If scaleFactor = 1.1, it means the image is reduced by 10% at each level
#faces is a array list of rectangles where each rectangle corresponds to a detected face.
#Each rectangle is described by 4 values: (x, y, w, h) — top-left corner coordinates, width, and height of the face.
print(len(eyes))
print(eyes)
for(x,y,w,h) in eyes:
    cv2.rectangle(img,[x,y],[w+x,h+y],[255,0,0],2)
cv2.imshow('eyes',img)
cv2.waitKey(0)


2
[[129  68  24  24]
 [ 90  69  26  26]]


-1

Two faces: test how scalar factor effects

In [58]:
import cv2 as cv
import numpy as np
facecascade=cv.CascadeClassifier(cv.data.haarcascades+'haarcascade_frontalface_default.xml')
eyecascade=cv.CascadeClassifier(cv.data.haarcascades+'haarcascade_eye.xml')
image=cv.imread(r"C:\Users\asus\Desktop\Computer Vision\lab3\jj.jpg")

gray=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
face=facecascade.detectMultiScale(gray,1.4,5)
print(len(face))
print(face)

for(x,y,w,h) in face:
    cv.rectangle(image,[x,y],[x+w,y+h],[255,0,0],2)

cv.imshow("final",image)
cv.waitKey(0)
    

2
[[283  50  66  66]
 [191  72  66  66]]


-1

In [42]:
array=np.array([[ 56 ,142, 273 ,273],[2,4,6,7]])
for i in array:
    print (i)



[ 56 142 273 273]
[2 4 6 7]


In [43]:
array=np.array([ 56 ,142, 273 ,273])
for i in array:
    print (i)

56
142
273
273


In [47]:
array=np.array([[ 56 ,142, 273 ,273],[2,4,6,7]])
for i in array:
    for j in i:
      print(j)

56
142
273
273
2
4
6
7


In [48]:
array=np.array([[ 56 ,142, 273 ,273],[2,4,6,7]])
for i,j in enumerate(array):
    print(i,j)

0 [ 56 142 273 273]
1 [2 4 6 7]


In [49]:
array=np.array([[ 56 ,142, 273 ,273],[2,4,6,7]])
for (x,y,b,m)in (array):
    print(x,y,b,m)

56 142 273 273
2 4 6 7


In [50]:
array=np.array([[ 56 ,142, 273 ,273],[2,4,6,7]])
for i in range (len(array)):
    print(i)

0
1


In [56]:
array=np.array([ 56 ,142, 273 ,273])
array2=np.array([ 1,2,3,4])
for i in zip(array,array2):
    print(i)

(np.int64(56), np.int64(1))
(np.int64(142), np.int64(2))
(np.int64(273), np.int64(3))
(np.int64(273), np.int64(4))


In [57]:
array=np.array([ 56 ,142, 273 ,273])
array2=np.array([ 1,2,3,4])
for i, j in zip(array,array2):
    print(i,j)

56 1
142 2
273 3
273 4
